services:
    rust:
        container_name: rust-web-app
        # image: my-rust:1.77.0-bookworm
        # image: rust:1.82.0-bookworm
        build:
            context: .
            dockerfile: Dockerfile

        tty: true
        environment:
            - TZ=Asia/Tokyo
        # volumes:
        #     - .:/app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/workspaces/rust-web-app
        working_dir: /workspaces/rust-web-app
        extra_hosts:
            - "host.docker.internal:host-gateway"