name: CI for book
on:
  push:
    branches: [main]
  pull_request:
    path-ignore:
      - "README.md"
      - "frontend/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rusty-book-manager

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: passwd
          POSTGRES_DB: app
        options: >-
          --health-cmd "pg_isready -U user -d app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1
      - uses: actions/checkout@v4

      # 2
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # 3
      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable

      # 4
      - name: Install cargo-related tools
        uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-make

      # 5
      - name: Tests compile
        run: cargo make test-ci --no-run --locked

      # 6
      - name: Test
        run: cargo make test-ci

      # 7
      - name: Clippy
        run: cargo make clippy-ci -- -Dwarnings

      # 8
      - name: Rustfmt
        run: cargo make fmt -- --check